version: '3.8'
services:
   jenkins:
      image: jenkins/jenkins:lts
      ports:
         - 8080:8080
         - 50000:50000
      container_name: jenkins
      privileged: true
      volumes:
        - ./jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock